# Setup
title: 心若向阳,无畏冰霜
description: Can1425 的小站
url: https://can1425.github.io
avatar: /imgs/75c5c66d17e14f7c8ff91c1b1a0843e6.jpg
paginate: 5
permalink: pretty
cover_image: /imgs/IMG_20221104_211105.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
weibo:
  username: 
  card: 
logo: 
social:
  name: Can1425
  links:
    - https://github.com/Can1425
google_site_verification: xxxxx
lang: cn

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Can1425
  url: https://github.com/Can1425/
  email: myqf1425@126.com
  
  # 侧边栏

sidebar: right

# 侧边栏启用哪些模块

widgets:

  - board # 公告

  - category # 分类

  - tag # 标签

  - tagcloud # 标签云

  - archive # 归档

  - recent_posts # 最近文章

# 归档列表的展示方式

archive_type: 'monthly' # 归档方式:  yearly | monthly

show_count: true # 显示每个归档的文章总数
